# Generated by Django 3.0.2 on 2020-03-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200303_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='allposts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
