# Generated by Django 3.0.2 on 2020-03-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200303_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='auther',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
