# Generated by Django 3.0.2 on 2020-03-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200303_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='auther',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
