# Generated by Django 3.0.2 on 2020-03-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20200303_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='allposts',
            field=models.TextField(max_length=5000),
        ),
    ]
